### ISSUE TITLE
The steps to detect pedestrian in video?

### ISSUE THREAD

**Issue by wn13083405221** [icsfy/Pedestrian_Detection#1]
I am sincerely consult for the The steps to detect pedestrian in video? thanks you @icsfy

**Comment by icsfy** [comment]
Please see the file `video_detect.cpp`, which contains the code to detect pedestrian in video

**Comment by wn13083405221** [comment]
thanks you for your reply,I have seen the file video_detect.cpp,but I don't know  the command to run the file? besides ,do you have the file" video.avi"? @icsfy

**Comment by icsfy** [comment]
@wn13083405221 
To compile executable file `VideoDetect`
```shell
$ cmake .
$ make
```
Use `VideoDetect <video_filename>` to detect , `<video_filename>` is your video file. 
For example:  `VideoDetect abc.avi`

**Comment by wn13083405221** [comment]
I want to do a project on the real-time  vehicle detection  in video, can i  have the opportunity  to consult you come questions,could you give me your contact information? such as QQ or  微信 ? thanks you @icsfy

**Comment by icsfy** [comment]
@wn13083405221 `QQ: 1294433495`
