### ISSUE TITLE
在执行./SvmTrainUseHog时会出现问题

### ISSUE THREAD

**Issue by ZHWXME** [icsfy/Pedestrian_Detection#2]
在执行./SvmTrainUseHog时会出现问题
libpng error: IDAT: invalid distance too far back

**Comment by icsfy** [comment]
我重新测试了一遍整个过程，没有遇到问题。我使用的libpng库版本是1.2.54
`libpng: /usr/lib/libpng12.so /usr/lib/libpng.a /usr/lib/libpng12.a /usr/lib/libpng.so /usr/include/libpng /usr/share/man/man3/libpng.3.gz`
会不会是你的libpng库的问题

**Comment by ZHWXME** [comment]
我用的是 mac ,安装的是libpng1.6.28

**Comment by icsfy** [comment]
看看这个是否能解决你的问题
http://stackoverflow.com/questions/25543930/libpng-error-idat-invalid-distance-too-far-back-in-mac-osx-10-9

**Comment by ZHWXME** [comment]
按照 stackoverflow 里的方法安装之后，问题没能解决，又提示了下面的错误..
Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib

**Comment by icsfy** [comment]
我没有mac，无法测试，这个问题只好你自己解决了

**Comment by ZHWXME** [comment]
好的 谢谢了

**Comment by houjincheng1992** [comment]
想问下这个问题解决了吗？
