### ISSUE TITLE
无法替换opencv中行人检测默认的那个分类器（cv::HOGDescriptor::setSVMDetector()）

### ISSUE THREAD

**Issue by Arthur-Shi** [icsfy/Pedestrian_Detection#4]
大神吖，我就换了数据库，别的都没变，已经能读取了图片，也训练完了，但是在替换的时候报了错，怎么就两个分类器的大小不一致了尼？

报错如下：
开始训练SVM分类器
训练完成
支持向量个数：1
检测子维数：94501
OpenCV Error: Assertion failed (checkDetectorSize()) in setSVMDetector, file /build/buildd/opencv-2.4.8+dfsg1/modules/objdetect/src/hog.cpp, line 89
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/objdetect/src/hog.cpp:89: error: (-215) checkDetectorSize() in function setSVMDetector

跪求解答。。。

**Comment by icsfy** [comment]
是不是图片大小不是64x128，你可以把图片裁剪成64x128试下看看可不可以

**Comment by Arthur-Shi** [comment]
没错。 谢谢！！！ 在训练的时候  图片尺寸和hog尺寸是 要完全吻合的，但是 检测的时候 不用 是吗？

**Comment by icsfy** [comment]
检测的时候是调用`detectMultiScale`对图片进行多尺度行人检测，可以看看`main.cpp`的195行后面读入图片进行检测的代码。

**Comment by Arthur-Shi** [comment]
我在尝试用我的数据库在做，我想把行人的检测框128*64改成64*64，理论上我觉得只要改了HOGDescriptor，就可以了 但是我在做的时候，发现：
开始训练SVM分类器
训练完成
支持向量个数：1
检测子维数：1765
OpenCV Error: Assertion failed (checkDetectorSize()) in setSVMDetector, file /build/buildd/opencv-2.4.8+dfsg1/modules/objdetect/src/hog.cpp, line 89
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/objdetect/src/hog.cpp:89: error: (-215) checkDetectorSize() in function setSVMDetector

卡在了	myHOG.setSVMDetector(myDetector);上，难道我是要去改opencv的源代码？ 还是在目前的文件夹里有哪个文件需要更改？
@icsfy 谢谢你的帮助in advance

**Comment by icsfy** [comment]
看opencv源代码里面的构造函数默认是64x128
```cpp
HOGDescriptor(Size win_size=Size(64, 128), Size block_size=Size(16, 16),
                  Size block_stride=Size(8, 8), Size cell_size=Size(8, 8),
                  int nbins=9, double win_sigma=DEFAULT_WIN_SIGMA,
                  double threshold_L2hys=0.2, bool gamma_correction=true,
                  int nlevels=DEFAULT_NLEVELS);
```
而184行应该是调用这个构造函数默认64x128，你可以像17行那样设置默认的窗口大小:
184行改为
```cpp
HOGDescriptor myHOG(Size(64,64),Size(16,16),Size(8,8),Size(8,8),9);
```

或者使用17行声明的hog:
注释掉184行:
```c
//HOGDescriptor myHOG;
```
然后将后面的`myHOG`（185行和199行）改成前面第17行声明的`hog`

**Comment by Arthur-Shi** [comment]
谢谢，超级无敌好用，就是效果还是不够理想，就算hardexamples了，总还是差点，过检率有点高。
不过还是超感谢的，帮上大忙了！！！

谢谢大神！！！

**Comment by Arthur-Shi** [comment]
我在尝试单尺度检测的时候，报错：
支持向量个数：1
检测子维数：1765
进行多尺度HOG人体检测
找到的矩形框个数：3
进行单尺度HOG人体检测
OpenCV Error: Sizes of input arguments do not match (The sample size is different from what has been used for training) in cvPreparePredictData, file /build/buildd/opencv-2.4.8+dfsg1/modules/ml/src/inner_functions.cpp, line 1114
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/ml/src/inner_functions.cpp:1114: error: (-209) The sample size is different from what has been used for training in function cvPreparePredictData

已放弃 (核心已转储)

然而我觉得是 这个 特征向量矩阵的错误，因为我改了64*64的检测框，所以 特征向量就变了
	Mat testFeatureMat = Mat::zeros(1,3780,CV_32FC1);//测试样本的特征向量矩阵

但是无论我是你原来写的3780还是 我的1765，都不行。
是为什么尼？

**Comment by Arthur-Shi** [comment]
而且 我的训练图片和检测图片尺寸都是64*64.为什么说我尺寸不对尼？

**Comment by Arthur-Shi** [comment]
改成1764，就可以了，谢谢大佬的代码！！！
