### ISSUE TITLE
how fast is this detector? Can it be used in Raspberry PI? 

### ISSUE THREAD

**Issue by Jiakui** [icsfy/Pedestrian_Detection#5]
For usage in raspberry pi, is this program fast enough?

Is this detector faster than yolo?

Thanks!

**Comment by icsfy** [comment]
It's slow

**Comment by zxinyang38** [comment]
@icsfy hi，how long does it take to run a picture?

**Comment by wyawya** [comment]
代码并没有实现裁剪图片的功能。由于肥料颗粒比较小，为了方便读者看清肥料颗粒的样子，我用图像处理软件手工裁剪的。------------------ 原始邮件 ------------------
发件人: "zxinyang38"<notifications@github.com>
发送时间: 2019年7月27日(星期六) 下午3:54
收件人: "icsfy/Pedestrian_Detection"<Pedestrian_Detection@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [icsfy/Pedestrian_Detection] how fast is this detector? Can it beused in Raspberry PI?  (#5)



@icsfy hi，how long does it take to run a picture?
 
&mdash;
